[19:56, 08/09/2025] 🙏🏼✝️: nano cloudbuild.yaml
[19:58, 08/09/2025] 🙏🏼✝️: # Build & Deploy OutBroker Web (Artifact Registry)
substitutions:
  _SERVICE: "outbroker-web"
  _REGION: "us-central1"
  _REPO: "outbroker"
  _CANONICAL: "outbroker.app"

options:
  logging: CLOUD_LOGGING_ONLY  # evita a exigência de bucket de logs

steps:
  # 1) Build da imagem com Buildpacks e envia para o Artifact Registry
  - name: gcr.io/k8s-skaffold/pack
    args:
      - 'build'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/$_REPO/$_SERVICE:$SHORT_SHA'

  # 2) Deploy no Cloud Run usando a imagem do Artifact Registry
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - $_SERVICE
      - --image=us-central1-docker.pkg.dev/$PROJECT_ID/$_REPO/$_SERVICE:$SHORT_SHA
      - --region=$_REGION
      - --platform=managed
      - --allow-unauthenticated
      - --set-env-vars=CANONICAL_HOST=$_CANONICAL

images:
  - us-central1-docker.pkg.dev/$PROJECT_ID/$_REPO/$_SERVICE:$SHORT_SHA
