# Build + Deploy Outbroker Web (Artifact Registry)

substitutions:
  _SERVICE: "outbroker-web"
  _REGION: "us-central1"
  _REPO: "outbroker-web"
  _CANONICAL: "outbroker.app"

options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # 1) Build da imagem com Buildpacks (publica no Artifact Registry)
  - id: Build image
    name: gcr.io/k8s-skaffold/pack
    args:
      - build
      - us-central1-docker.pkg.dev/$PROJECT_ID/$_REPO/$_SERVICE:$SHORT_SHA
      - --builder
      - gcr.io/buildpacks/builder:latest
      - --publish

  # 2) Deploy no Cloud Run usando a imagem publicada
  - id: Deploy to Cloud Run
    name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    entrypoint: gcloud
    args:
      - run
      - deploy
      - $_SERVICE
      - --image=us-central1-docker.pkg.dev/$PROJECT_ID/$_REPO/$_SERVICE:$SHORT_SHA
      - --region=$_REGION
      - --platform=managed
      - --allow-unauthenticated
      - --set-env-vars
      - CANONICAL_HOST=$_CANONICAL

images:
  - us-central1-docker.pkg.dev/$PROJECT_ID/$_REPO/$_SERVICE:$SHORT_SHA
