options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _SERVICE: outbroker-web
  _REGION: us-central1
  _IMAGE: us-central1-docker.pkg.dev/$PROJECT_ID/outbroker/outbroker-web:$COMMIT_SHA

steps:
  - id: Build image
    name: gcr.io/k8s-skaffold/pack
    args:
      - build
      - $_IMAGE
      - --builder
      - gcr.io/buildpacks/builder

  - id: Deploy to Cloud Run
    name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    entrypoint: gcloud
    args:
      - run
      - deploy
      - $_SERVICE
      - --image
      - $_IMAGE
      - --region
      - $_REGION
      - --platform
      - managed
      - --allow-unauthenticated

images:
  - $_IMAGE
