# Build & Deploy OutBroker Web (Artifact Registry)

substitutions:
  _SERVICE: "outbroker-web"
  _REGION: "us-central1"
  _REPO: "outbroker-web"        # nome do repositório no Artifact Registry
  _CANONICAL: "outbroker.app"

options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # 1 Build da imagem com Buildpacks (publica direto no Artifact Registry)
- id: Build image
  name: gcr.io/k8s-skaffold/pack
  entrypoint: bash
  args:
    - -c
    - |
      set -e
      pack version
      pack config default-builder gcr.io/buildpacks/builder:latest
      pack build "us-central1-docker.pkg.dev/$PROJECT_ID/$_REPO/$_SERVICE:$SHORT_SHA" --builder gcr.io/buildpacks/builder:latest --publish
